"use client";
import{useState,useEffect,useRef,type CSSProperties}from'react';
import{Progress}from'@/components/ui/progress';
import{SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarInset,useSidebar}from'@/components/ui/sidebar';
import{Button}from'@/components/ui/button';
import{SlidersHorizontal,Check,CircleHelp,Menu,Sigma,FlaskConical,Target,Repeat2,ScanLine,MoveUpRight}from'lucide-react';
import{FitLab}from'@/components/fit-lab';
import{ModelLab,SamplingLab}from'@/components/model-sampling';
import{InferenceLab}from'@/components/inference-lab';
import{DiagnosisLab,CausalLab}from'@/components/diagnosis-causal';
import{FinalChallenge}from'@/components/final-challenge';
const lessons=[{title:'亲手拟合一条线',short:'最小二乘',icon:SlidersHorizontal,kicker:'把「贴合」变成一个可以比较的数',headline:'这条线，凭什么最好？'},{title:'让模型生出数据',short:'条件均值与误差',icon:FlaskConical,kicker:'每一个 x 背后，都有一群可能的 y',headline:'直线上住的，是平均值。'},{title:'如果研究重来一次',short:'抽样分布与无偏性',icon:Repeat2,kicker:'让同一个世界，交出不同的样本',headline:'样本会换，答案会晃。'},{title:'给不确定性量尺寸',short:'标准误与区间',icon:ScanLine,kicker:'用一份样本，估计答案会晃多远',headline:'一个数字，还不够。'},{title:'去残差里找线索',short:'假设与诊断',icon:CircleHelp,kicker:'让模型没有解释的部分，继续说话',headline:'看起来很直，就够了吗？'},{title:'预测好，不等于因果',short:'关联、预测与干预',icon:MoveUpRight,kicker:'同一条回归线，可以回答哪种问题？',headline:'冷饮能让空调更费电？'},{title:'直觉通关挑战',short:'把知识变成判断',icon:Target,kicker:'现在，轮到你识破统计里的小陷阱',headline:'别背答案，讲出理由。'}];
function Navigation({active,onSelect,solved}:{active:number;onSelect:(i:number)=>void;solved:Set<string>}){const{setOpenMobile}=useSidebar();const keys=['fit','model','sampling','interval','diagnosis','causal'];return <Sidebar className="lab-sidebar"><SidebarHeader><div className="brand"><div className="brand-icon">β</div><div>回归游乐场<small>线性回归 · 交互实验</small></div></div></SidebarHeader><SidebarContent><div className="sidebar-caption">一条线背后的七次追问</div><SidebarMenu>{lessons.map((l,i)=>{const Icon=l.icon;return <SidebarMenuItem key={l.title}><SidebarMenuButton isActive={active===i} className="lesson-nav" onClick={()=>{onSelect(i);setOpenMobile(false);}}><span className="lesson-num">{(i+1).toString().padStart(2,'0')}</span><div><span>{l.title}</span><small>{l.short}</small></div>{(i<6?solved.has(keys[i]):Array.from(solved).filter(k=>k.startsWith('final')).length===8)?<Check size={17} className="nav-done"/>:<Icon size={16} className="nav-icon"/>}</SidebarMenuButton></SidebarMenuItem>;})}</SidebarMenu><div className="sidebar-thinking"><Sigma size={23}/><p>先猜一猜，<br/>再让数据说话。</p><span>直觉，要经得起重来一次。</span></div></SidebarContent><SidebarFooter><div className="side-progress"><span>已解挑战</span><span>{solved.size} / 14</span></div><Progress value={solved.size/14*100} aria-label={`已解 ${solved.size} 道，共 14 道挑战`}/><p className="sidebar-bottom">把公式变成看得见的判断</p></SidebarFooter></Sidebar>;}
function LearningApp(){const[active,setActive]=useState(0),[solved,setSolved]=useState<Set<string>>(new Set());const{toggleSidebar}=useSidebar();const solve=(id:string)=>setSolved(s=>new Set(s).add(id));function navigate(i:number){setActive(i);window.scrollTo({top:0,behavior:'instant'});}const current=lessons[active];
const stateRef=useRef({active,solved});stateRef.current={active,solved};
const pending=useRef<((value:unknown)=>void)|null>(null);
useEffect(()=>{pending.current?.({experiment:active+1,title:lessons[active].title});pending.current=null;},[active]);
useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:unknown)=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();
const entries=[{name:'get_regression_learning_state',title:'读取回归学习进度',description:'Read the current experiment and the number of correctly solved learning challenges.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>({experiment:stateRef.current.active+1,title:lessons[stateRef.current.active].title,solvedChallenges:stateRef.current.solved.size,totalChallenges:14})},{name:'open_regression_experiment',title:'打开一个回归实验',description:'Navigate to one of seven regression learning experiments. This only changes the visible experiment, preserving the current session learning state.',inputSchema:{type:'object',properties:{experiment:{type:'integer',minimum:1,maximum:7}},required:['experiment'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Array.isArray(input))throw new Error('experiment must be an integer from 1 to 7');const value=input as Record<string,unknown>;const number=value.experiment;if(Object.keys(value).some(k=>k!=='experiment')||typeof number!=='number'||!Number.isInteger(number)||number<1||number>7)throw new Error('experiment must be an integer from 1 to 7');if(stateRef.current.active===number-1)return{experiment:number,title:lessons[number-1].title};return new Promise(resolve=>{pending.current=resolve;setActive(number-1);window.scrollTo({top:0,behavior:'instant'});});}}];
for(const entry of entries){try{void Promise.resolve(context.registerTool(entry,{signal:lifecycle.signal})).catch(()=>{});}catch{}}return()=>lifecycle.abort();},[]);
return <><Navigation active={active} onSelect={navigate} solved={solved}/><SidebarInset className="app-main"><header className="topbar"><div className="topbar-left"><Button variant="ghost" size="icon" className="mobile-menu" aria-label="打开学习目录" onClick={toggleSidebar}><Menu size={20}/></Button><span>线性回归</span><span className="topbar-slash">/</span><span>{current.short}</span></div><div className="topbar-progress"><span>边玩边懂</span><span className="chapter-pill">{String(active+1).padStart(2,'0')} / 07</span></div></header><div className="lesson-content"><div className="lesson-heading"><div className="eyebrow"><span>实验 {String(active+1).padStart(2,'0')}</span><i/>{current.kicker}</div><h1>{current.headline}</h1></div><div hidden={active!==0}><FitLab solved={solved} onSolve={solve}/></div><div hidden={active!==1}><ModelLab solved={solved} onSolve={solve}/></div><div hidden={active!==2}><SamplingLab solved={solved} onSolve={solve}/></div><div hidden={active!==3}><InferenceLab solved={solved} onSolve={solve}/></div><div hidden={active!==4}><DiagnosisLab solved={solved} onSolve={solve}/></div><div hidden={active!==5}><CausalLab solved={solved} onSolve={solve}/></div><div hidden={active!==6}><FinalChallenge solved={solved} onSolve={solve}/></div><div className="lesson-navigation"><span>{active+1} / 7</span><div>{active>0&&<Button variant="outline" onClick={()=>navigate(active-1)}>上一个实验</Button>}{active<6&&<Button className="next-lesson" onClick={()=>navigate(active+1)}>继续：{lessons[active+1].title}</Button>}</div></div></div></SidebarInset></>;}
export default function Home(){return <SidebarProvider style={{'--sidebar-width':'245px'} as CSSProperties}><LearningApp/></SidebarProvider>;}
