"use client";
import{useState}from'react';
import{Button}from'@/components/ui/button';
import{Progress}from'@/components/ui/progress';
import{Check,Target,Sparkles}from'lucide-react';
import{Quiz,Talk,type Question,type LabProps}from'@/components/learning-ui';
const questions:Question[]=[
 {id:'final1',prompt:'这一轮得到斜率 b₁ = 1.7。哪个说法最准确？',options:['总体参数被我们改成了 1.7','1.7 是这批样本产生的估计值','估计量永远是固定数字 1.7'],correct:1,feedback:['拟合不会修改总体。它用已观察到的样本，估计总体中的目标。','参数是目标，估计量是把样本变成答案的规则，估计值是这一轮具体交出的数字。','估计量在抽样前有随机性。1.7 只是它本次实现的数值。']},
 {id:'final2',prompt:'设 E[X]=0，Y=2+1.8X+ε，ε=0.6X+U，且 E[U|X]=0。条件均值的斜率是多少？',options:['1.8，因为 E[ε]=0','2.4，因为 E[ε|X]=0.6X','0.6，因为误差决定了全部趋势'],correct:1,feedback:['全体误差平均为零还不够。不同 x 下的平均误差并不是零。','把条件均值展开：E[Y|X]=2+(1.8+0.6)X。指定生成式中的 1.8，并不是这时的条件均值斜率。','条件均值同时包含 1.8X 和 0.6X，要把它们加起来。']},
 {id:'final3',prompt:'真实斜率是 2，一次研究估出 1.4。这能证明估计量有偏吗？',options:['能，没猜中就是有偏','不能，要看重复抽样分布的期望','不能，因为任何估计量都无偏'],correct:1,feedback:['一次估计误差不等于系统偏差。无偏方法也会在某一次偏得很远。','无偏性看长期中心是否对准真值，方差看答案的分散。一发打歪没有替整套方法定性。','给每次估计都固定加上 1，就能制造有偏估计量。']},
 {id:'final4',prompt:'噪声 σ 不变，Sₓₓ 变成原来的 4 倍。理论斜率 SE 怎样变？',options:['变成 1/2','变成 1/4','不变，因为人数可能没变'],correct:0,feedback:['SE=σ/√Sₓₓ。分母扩大 2 倍，标准误减半。','变成四分之一的是方差。标准误是方差的平方根。','人数只是信息的一部分。相同人数在横向分得更开，也能更好辨认斜率。']},
 {id:'final5',prompt:'条件均值线性且误差条件均值为零，但右边波动更大。最合理的判断是？',options:['OLS 斜率必然有偏','OLS 仍可无偏，常规 SE 可能失准','只要改用 HC3，就自动得到因果结论'],correct:1,feedback:['异方差本身不破坏条件均值零。要分清点估计与标准误分别受什么影响。','可以考虑适当的异方差稳健推断；若方差模型可靠，也可考虑加权方法。','HC3 调整方差估计，不会排除混杂，也不会自动修正均值错设或序列相关。']},
 {id:'final6',prompt:'正态线性回归中的「正态」，主要要求谁服从正态？',options:['自变量 X','把所有人的 Y 混在一起后的边际分布','给定设计后，误差的条件联合分布'],correct:2,feedback:['X 可以是固定设计，完全不必正态。','不同 x 的均值不同，所有 Y 混在一起，未必呈正态。看的是给定 x 后的波动规律。','经典正态模型对给定 X 后的误差作联合正态、同方差、独立等规定，进而得到精确的小样本 t 推断。']},
 {id:'final7',prompt:'某方差估计 V̂ 无偏。把它开平方，标准差估计也一定无偏吗？',options:['一定，开平方不会影响平均','不一定，非线性变换不能直接穿过期望','不一定，所以原来的方差估计也必然有偏'],correct:1,feedback:['平均「先开方的结果」通常不同于「先平均再开方」。','一般 E[√V̂] ≠ √E[V̂]。平方根是凹函数，非负方差估计开方后通常有向下偏差。','前面的无偏结论仍可成立。变化出现在对估计量做了非线性变换之后。']},
 {id:'final8',prompt:'斜率检验给出 p=0.02，可以怎样解读？',options:['零假设为真的概率是 2%','在零假设与模型成立时，出现当前或更极端统计量的概率是 2%','这个变量有 98% 的概率造成了结果'],correct:1,feedback:['p 值是在假定零假设成立后计算的概率，不能反过来当成零假设成立的概率。','还要结合估计值、区间、模型诊断和研究设计，才能判断实际意义与解释范围。','显著性既不是效应大小，也不是因果概率。']}
];
export function FinalChallenge({solved,onSolve}:LabProps){const[step,setStep]=useState(0);const done=questions.filter(q=>solved.has(q.id)).length;return <><div className="challenge-header"><div><span className="section-label"><Target size={18}/>最后八次追问</span><p>小问：这次不能只说「我懂了」。<br/>阿 β：选一个答案，再看看你的理由站不站得住。</p></div><div className="challenge-score"><strong>{done}<small>/ 8</small></strong><Progress value={done/8*100} aria-label={`已答对 ${done} 题`}/></div></div><div className="question-steps">{questions.map((q,i)=><Button key={q.id} variant="outline" aria-label={`第 ${i+1} 题${solved.has(q.id)?'，已理解':''}`} aria-current={step===i?'step':undefined} className={step===i?'selected':''} onClick={()=>setStep(i)}>{solved.has(q.id)?<Check size={16}/>:String(i+1).padStart(2,'0')}</Button>)}</div>{questions.map((q,i)=><div key={q.id} hidden={step!==i}><Quiz q={q} solved={solved.has(q.id)} onSolve={onSolve}/></div>)}<div className="challenge-actions"><Button variant="outline" onClick={()=>setStep(v=>v-1)} disabled={step===0}>上一题</Button><span>{step+1} / 8</span><Button className="primary-action" onClick={()=>setStep(v=>v+1)} disabled={step===7}>下一题</Button></div>{done===8&&<div className="completion"><Sparkles size={25}/><div><h2>这一次，你看见了线背后的统计学。</h2><p>会拟合，会追问抽样波动，会区分假设的分工，也会在因果结论前多想一步。</p></div></div>}<div className="knowledge-map"><h2>把七个实验，连成一套判断</h2>{[['眼前这批点','用损失函数明确「好」是什么，计算拟合线。'],['背后那个世界','用条件均值与误差规律描述数据如何生成。'],['重来一次研究','用抽样分布理解估计量的无偏性与波动。'],['一份样本的局限','用标准误和区间量化不确定性，分清均值与个体。'],['模型有没有漏听','从残差、波动和顺序里找线索，检查推断条件。'],['结论能走多远','区分关联、预测与干预，回到研究设计。']].map(([title,text],i)=><div className="knowledge-row" key={title}><span>{String(i+1).padStart(2,'0')}</span><h3>{title}</h3><p>{text}</p></div>)}</div><Talk question="所以，线性回归最重要的公式是哪一个？"><p>公式当然重要，但更重要的是每次都能回答：我在估计什么？如果换一批样本会怎样？这个结论依靠什么条件？</p></Talk></>;}
