"use client";
import {useState,useEffect,useRef,useId,type ReactNode,type PointerEvent} from 'react';
import {Slider} from '@/components/ui/slider';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from '@/components/ui/accordion';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Sparkles,BookOpen,Target,Check,CheckCircle2,X as XIcon} from 'lucide-react';
import {fmt,type Point} from '@/lib/regression';
export const BLUE='#3267d6',ORANGE='#d96944',GREEN='#378266',INK='#253c59';
export type LabProps={solved:Set<string>;onSolve:(id:string)=>void};
export function Range({label,value,onChange,min,max,step=1,suffix='',digits=0}:{label:string;value:number;onChange:(n:number)=>void;min:number;max:number;step?:number;suffix?:string;digits?:number}){const id=useId();return <div className="range-control"><div className="range-label"><label id={id}>{label}</label><output>{fmt(value,digits)}{suffix}</output></div><Slider value={[value]} onValueChange={([v])=>onChange(v)} min={min} max={max} step={step} aria-labelledby={id}/><div className="range-ends"><span>{min}{suffix}</span><span>{max}{suffix}</span></div></div>;}
export function Segments({value,onChange,options,label}:{value:string;onChange:(s:string)=>void;options:[string,string][];label:string}){return <Tabs value={value} onValueChange={onChange} className="segments"><TabsList aria-label={label}>{options.map(([v,t])=><TabsTrigger key={v} value={v}>{t}</TabsTrigger>)}</TabsList></Tabs>;}
export function Talk({question,children}:{question:string;children:ReactNode}){return <div className="dialogue"><div className="question"><span className="speaker">小问</span><p>{question}</p></div><div className="answer"><span className="speaker professor">阿 β</span><div>{children}</div></div></div>;}
export function Insight({children,label='抓住这件事'}:{children:ReactNode;label?:string}){return <div className="insight"><Sparkles size={18}/><div><span>{label}</span><p>{children}</p></div></div>;}
export function Formula({children}:{children:ReactNode}){return <div className="formula">{children}</div>;}
export function Frac({top,bottom}:{top:ReactNode;bottom:ReactNode}){return <span className="frac"><span>{top}</span><span>{bottom}</span></span>;}
export function Deeper({items}:{items:{title:string;content:ReactNode}[]}){return <div className="deeper"><div className="section-label"><BookOpen size={16}/> 再往里想一层</div><Accordion type="multiple">{items.map((i,k)=><AccordionItem key={k} value={String(k)}><AccordionTrigger>{i.title}</AccordionTrigger><AccordionContent><div className="explanation">{i.content}</div></AccordionContent></AccordionItem>)}</Accordion></div>;}
export function Metric({label,value,note,color}:{label:string;value:ReactNode;note?:string;color?:string}){return <div className="metric"><span>{label}</span><strong style={{color}}>{value}</strong>{note&&<small>{note}</small>}</div>;}
export type PlotTools={X:(x:number)=>number;Y:(y:number)=>number;width:number;height:number;left:number;right:number;top:number;bottom:number};
export function Plot({xDomain=[0,10],yDomain=[0,16],xLabel='x',yLabel='y',height=350,children,label,onMove,onUp}:{xDomain?:number[];yDomain?:number[];xLabel?:string;yLabel?:string;height?:number;children:(p:PlotTools)=>ReactNode;label:string;onMove?:(e:PointerEvent<SVGSVGElement>,p:PlotTools)=>void;onUp?:()=>void}){const ref=useRef<HTMLDivElement>(null);const[width,setWidth]=useState(640);const cid=useId().replace(/:/g,'');useEffect(()=>{if(!ref.current)return;const ro=new ResizeObserver(([e])=>{if(e.contentRect.width>100)setWidth(Math.floor(e.contentRect.width));});ro.observe(ref.current);return()=>ro.disconnect();},[]);const left=48,right=20,top=30,bottom=46;const X=(x:number)=>Math.round((left+(x-xDomain[0])/(xDomain[1]-xDomain[0])*(width-left-right))*1000)/1000,Y=(y:number)=>Math.round((height-bottom-(y-yDomain[0])/(yDomain[1]-yDomain[0])*(height-top-bottom))*1000)/1000;const p={X,Y,width,height,left,right,top,bottom};const ticks=Array.from({length:5},(_,i)=>i/4);return <div className="plot" ref={ref}><svg viewBox={`0 0 ${width} ${height}`} role={onMove?"group":"img"} aria-label={label} onPointerMove={e=>onMove?.(e,p)} onPointerUp={onUp} onPointerCancel={onUp}><defs><clipPath id={cid}><rect x={left} y={top} width={width-left-right} height={height-top-bottom}/></clipPath></defs>{ticks.map(t=>{const y=yDomain[0]+t*(yDomain[1]-yDomain[0]),x=xDomain[0]+t*(xDomain[1]-xDomain[0]);return <g key={t}><line className="gridline" x1={left} x2={width-right} y1={Y(y)} y2={Y(y)}/><line className="gridline" x1={X(x)} x2={X(x)} y1={top} y2={height-bottom}/><text className="tick" x={left-11} y={Y(y)+4} textAnchor="end">{Math.abs(y)>=100?fmt(y,0):fmt(y,Math.abs(y)%1<.01?0:1)}</text><text className="tick" x={X(x)} y={height-bottom+24} textAnchor="middle">{fmt(x,Math.abs(x)%1<.01?0:1)}</text></g>;})}<text className="axis-label" x={left} y={17}>{yLabel}</text><text className="axis-label" x={width-right} y={height-7} textAnchor="end">{xLabel}</text><g clipPath={`url(#${cid})`}>{children(p)}</g></svg></div>;}
export function Dots({points,X,Y,color=INK,r=4,opacity=.7}:{points:Point[];X:(n:number)=>number;Y:(n:number)=>number;color?:string;r?:number;opacity?:number}){return <>{points.map((p,i)=><circle key={i} cx={X(p.x)} cy={Y(p.y)} r={r} fill={color} opacity={opacity}><title>{`x=${fmt(p.x)}, y=${fmt(p.y)}`}</title></circle>)}</>;}
export function Curve({fn,X,Y,from=0,to=10,color=BLUE,dash='',stroke=2.7}:{fn:(x:number)=>number;X:(x:number)=>number;Y:(y:number)=>number;from?:number;to?:number;color?:string;dash?:string;stroke?:number}){return <path d={Array.from({length:101},(_,i)=>{const x=from+(to-from)*i/100;return `${i?'L':'M'} ${X(x)} ${Y(fn(x))}`;}).join(' ')} fill="none" stroke={color} strokeWidth={stroke} strokeDasharray={dash}/>;}
export function Legend({items}:{items:[string,string][]}){return <div className="legend">{items.map(([c,t])=><span key={t}><i style={{background:c}}/>{t}</span>)}</div>;}
export type Question={id:string;prompt:string;options:string[];correct:number;feedback:string[]};
export function Quiz({q,solved,onSolve}:{q:Question;solved:boolean;onSolve:(id:string)=>void}){const[choice,setChoice]=useState<number|null>(null);const id=useId();return <div className={`quiz ${choice===q.correct?'is-correct':''}`}><div className="section-label"><Target size={17}/> 直觉小挑战{solved&&<span className="solved-label"><Check size={14}/>已理解</span>}</div><h3>{q.prompt}</h3><RadioGroup value={choice===null?'':String(choice)} onValueChange={v=>{const n=Number(v);setChoice(n);if(n===q.correct)onSolve(q.id);}} className="quiz-options">{q.options.map((o,i)=><label className={`quiz-option ${choice===i?'chosen':''}`} key={i} htmlFor={`${id}-${i}`}><RadioGroupItem id={`${id}-${i}`} value={String(i)}/><span>{o}</span>{choice===i&&(i===q.correct?<CheckCircle2 size={18}/>:<XIcon size={18}/>)}</label>)}</RadioGroup>{choice!==null&&<div className={`quiz-feedback ${choice===q.correct?'right':'wrong'}`} role="status"><span>{choice===q.correct?'阿 β：对，就是这个意思。':'阿 β：再想一步。'}</span>{q.feedback[choice]}</div>}</div>;}
